# Generated by Django 4.0.5 on 2022-06-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produitFournisseur', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='etat',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='etat',
            new_name='state',
        ),
    ]
