# Generated by Django 4.0.5 on 2022-06-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0002_article_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abc',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='article',
            name='qte',
            field=models.IntegerField(default=0),
        ),
    ]
