# Generated by Django 4.0.5 on 2022-06-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionDepartement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('poste', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=200)),
                ('adresse', models.CharField(blank=True, default='', max_length=200)),
                ('attachedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDepartement.departement')),
            ],
        ),
    ]
