# Generated by Django 4.0.5 on 2022-06-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=1000)),
                ('Email', models.EmailField(max_length=100)),
            ],
        ),
    ]
